blank_issues_enabled: false
contact_links:
  - name: Feature requests and ideas
    url: https://github.com/Umbraco/Umbraco.Compose.Intergations/discussions
    about: Please discuss feature requests and ideas in our discussions board