// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UmbracoCompose.Cli.Clients.Ingestion.V1.Item.Item;
namespace UmbracoCompose.Cli.Clients.Ingestion.V1.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{projectAlias}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class WithProjectAliasItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the UmbracoCompose.Cli.Clients.Ingestion.v1.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::UmbracoCompose.Cli.Clients.Ingestion.V1.Item.Item.WithEnvironmentAliasItemRequestBuilder"/></returns>
        public global::UmbracoCompose.Cli.Clients.Ingestion.V1.Item.Item.WithEnvironmentAliasItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("environmentAlias", position);
                return new global::UmbracoCompose.Cli.Clients.Ingestion.V1.Item.Item.WithEnvironmentAliasItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoCompose.Cli.Clients.Ingestion.V1.Item.WithProjectAliasItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectAliasItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{projectAlias}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoCompose.Cli.Clients.Ingestion.V1.Item.WithProjectAliasItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectAliasItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{projectAlias}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
