// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.Item;
namespace Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\{projectAlias}\{environmentAlias}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class WithEnvironmentAliasItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Umbraco.Compose.Cli.Clients.Ingestion.v1.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.Item.WithCollectionAliasItemRequestBuilder"/></returns>
        public global::Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.Item.WithCollectionAliasItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("collectionAlias", position);
                return new global::Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.Item.WithCollectionAliasItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.WithEnvironmentAliasItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnvironmentAliasItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{projectAlias}/{environmentAlias}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Umbraco.Compose.Cli.Clients.Ingestion.V1.Item.Item.WithEnvironmentAliasItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnvironmentAliasItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/{projectAlias}/{environmentAlias}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
