// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UmbracoCompose.Cli.Clients.Ingestion.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal partial class ContentEntry : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
        public global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry_action? Action { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Data { get; set; }
#nullable restore
#else
        public UntypedNode Data { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The operations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Operations { get; set; }
#nullable restore
#else
        public UntypedNode Operations { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The variant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Variant { get; set; }
#nullable restore
#else
        public string Variant { get; set; }
#endif
        /// <summary>The where property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Where { get; set; }
#nullable restore
#else
        public UntypedNode Where { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry_action>(); } },
                { "data", n => { Data = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "operations", n => { Operations = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "variant", n => { Variant = n.GetStringValue(); } },
                { "where", n => { Where = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::UmbracoCompose.Cli.Clients.Ingestion.Models.ContentEntry_action>("action", Action);
            writer.WriteObjectValue<UntypedNode>("data", Data);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("operations", Operations);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("variant", Variant);
            writer.WriteObjectValue<UntypedNode>("where", Where);
        }
    }
}
#pragma warning restore CS0618
