// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace UmbracoCompose.Cli.Clients.Ingestion.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum ContentEntry_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "upsert")]
        #pragma warning disable CS1591
        Upsert,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "patch")]
        #pragma warning disable CS1591
        Patch,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge-patch")]
        #pragma warning disable CS1591
        MergePatch,
        #pragma warning restore CS1591
    }
}
